<%@ include file="headerfile.jsp"%>
<title>TryKaro-India's First Website To Try Wide Range Of
	Products</title>
<meta name="title"
	content="Try Latest Mobile, Cameras, Gaming Console, Fashion Apparels &amp; Beauty Products @ Trykaro.com">
<meta name="description"
	content="TryKaro.com - India's first website to try wide range of products including Electronics, Clothes And Beauty Care Products.Try personalized samples which suites you plus get ideas and inspiration to do experiment in your daily routine. Cash on delivery and Subscription also available">
<meta name="keywords"
	content="TryKaro,Try Karo,try mobiles,try fashion apparels,beauty product samples,fragrances trial,try in india,beauty box,dress bag,gadget box ">
<meta property="og:title"
	content="TryKaro.com - India's First Website To Try Wide Range Of Products" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://www.trykaro.com" />
<meta property="og:image" content="res/img/logo.png" />
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@TryKaro" />
<meta name="twitter:title"
	content="TryKaro.com - India's First Website To Try Wide Range Of Products" />
<meta name="twitter:description"
	content="TryKaro.com - India's first website to try wide range of products including Electronics, Clothes And Beauty Care Products.Try personalized samples which suites you plus get ideas and inspiration to do experiment in your daily routine. Cash on delivery and Subscription also available." />
<meta name="robots" content="index, follow">
<meta name="twitter:image" content="res/img/logo.png" />
</head>
<body class="body-class">
	<!-- LOADING -->
	<div class="loading-container" id="loading">
		<div class="loading-inner">
			<div class="windows8">
				<div class="wBall" id="wBall_1">
					<div class="wInnerBall"></div>
				</div>
				<div class="wBall" id="wBall_2">
					<div class="wInnerBall"></div>
				</div>
				<div class="wBall" id="wBall_3">
					<div class="wInnerBall"></div>
				</div>
				<div class="wBall" id="wBall_4">
					<div class="wInnerBall"></div>
				</div>
				<div class="wBall" id="wBall_5">
					<div class="wInnerBall"></div>
				</div>
			</div>
		</div>
	</div>
	<!-- END LOADING -->
	<%@ include file="navigation.jsp"%>
	<div class="wrap-page">
		<section class="login-register listtextt">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="heading _two text-left">
							<h1>Terms & Conditions</h1>
						</div>
						<div class="form login ">
							<p>Last updated: 15, April 2016</p>
							<p class="condition listtext">
								<b>This document is an electronic record in terms of
									Information Technology Act, 2000 and rules there under as
									applicable and the amended provisions pertaining to electronic
									records in various statutes as amended by the Information
									Technology Act, 2000. This electronic record is generated by a
									computer system and does not require any physical or digital
									signatures. </b>
							</p>
							<p class="condition listtext">
								This document is published in accordance with the provisions of
								Rule 3 (1) of the Information Technology (Intermediaries
								guidelines) Rules, 2011 that require publishing the rules and
								regulations, privacy policy and Terms of Use for access or usage
								of <b>www.trykaro.in</b> website.
							</p>
							<p class="condition listtext">
								<b> ACCESSING, BROWSING OR OTHERWISE USING THE SITE
									INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER
									THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY
									BEFORE PROCEEDING.</b> By impliedly or expressly accepting these
								Terms of Use, You also accept and agree to be bound by TryKaro
								Policies (including but not limited to Privacy Policy available
								on /s/privacy policy) as amended from time to time.
							</p>
							<p class="condition listtext">
								<b>ARBITRATION NOTICE: EXCEPT FOR CERTAIN TYPES OF DISPUTES
									DESCRIBED IN THE ARBITRATION CLAUSE BELOW, YOU AGREE THAT
									DISPUTES BETWEEN YOU AND TRYKARO WILL BE RESOLVED BY MANDATORY
									BINDING ARBITRATION AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A
									CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</b>
							</p>
							<br />
							<h3>Have Fun</h3>
							<p class="condition listtext">Although these Terms form a
								proper legal contract and inevitably read like a proper legal
								contract the bulk of them are simply designed to ensure our
								users have fun. These Terms let us provide and continue to
								improve our Services, while at the same time ensuring that a few
								mean users don't ruin the fun for everyone else. Your part in
								that is simple. Just use common sense: Keep trying awesome
								products and don't indulge in any kind of forge request and
								payment methodology.</p>
							<h3>Our Audience</h3>
							<p class="condition listtext">Use of the Website is available
								only to persons who can form legally binding contracts under
								Indian Contract Act, 1872. Persons who are "incompetent to
								contract" within the meaning of the Indian Contract Act, 1872
								including minors, un-discharged insolvents etc. are not eligible
								to use the Website. If you are a minor i.e. under the age of 18
								years, you shall not register as a User of the TryKaro website
								and shall not transact on or use the website. As a minor if you
								wish to use or transact on website, such use or transaction may
								be made by your legal guardian or parents on the Website.
								TryKaro reserves the right to terminate your membership and / or
								refuse to provide you with access to the Website if it is
								brought to TryKaro's notice or if it is discovered that you are
								under the age of 18 years.</p>
							<h3>Privacy</h3>
							<p class="condition listtext">We view protection of your
								privacy as a very important principle. We understand clearly
								that you and your personal information is one of our most
								important assets. We store and process your information
								including any sensitive financial information collected (as
								defined under the Information Technology Act, 2000), if any, on
								computers that may be protected by physical as well as
								reasonable technological security measures and procedures in
								accordance with Information Technology Act 2000 and rules
								thereunder. Our current privacy policy is available at our
								website. If you object to your information being transferred or
								used in this way please do not use our website. We and our
								affiliates will share / sell / transfer / license / convey some
								or all of your personal information with another business entity
								should we (or our assets) plan to merge with or are acquired by
								that business entity, or re-organization, amalgamation,
								restructuring of business or for any other reason whatsoever.
								Should such a transaction or situation occur, the other business
								entity or the new combined entity will be required to follow the
								privacy policy with respect to your personal information. Once
								you share your information with us, we and our affiliate may use
								such information to provide you various services with respect to
								your transaction whether such transactions are conducted on
								www.trykaro.in or with third party merchant's or third party
								merchant's website.</p>
							<h3>Communication</h3>
							<p class="condition listtext">When you use the website or
								send emails or other data, information or communication with us,
								You agree and understand that you are communicating with us
								through electronic records and you consent to receive
								communications via electronic records from us periodically and
								as and when required. We may communicate with you by email or by
								such other mode of communication, electronic or otherwise.</p>
							<h3>Feedback</h3>
							<p class="condition listtext">You agree that any feedback,
								suggestions, ideas, or other information or materials regarding
								TryKaro or the Services that you provide, whether by email or
								otherwise ("Feedback"), are non-confidential and shall become
								the sole property of TryKaro. We will be entitled to the
								unrestricted use and dissemination of such feedback for any
								purpose, commercial or otherwise, without acknowledging or
								compensating you. You waive any rights you may have the feedback
								(including any copyrights or moral rights). We like hearing from
								users, but please do not share your ideas with us if you expect
								to be paid or want to continue to own or claim rights in them.</p>
							<h3>TryKaro Content</h3>
							<p class="condition listtext">All text, graphics, user
								interfaces, visual interfaces, photographs, trademarks, logos,
								sounds, music and artwork (collectively, "Content"), is a third
								party user generated content and TryKaro has no control over
								such third party user generated content as TryKaro is merely an
								intermediary for the purposes of its Terms of Use. Except as
								expressly provided in these Terms of Use, no part of the website
								and no content may be copied, reproduced, republished, uploaded,
								posted, publicly displayed, encoded, translated, transmitted or
								distributed in any way (including "mirroring") to any other
								computer, server, website or other medium for publication or
								distribution or for any commercial enterprise, without TryKaro's
								express prior written consent. You may use information on the
								products and services purposely made available on the website
								for downloading, provided that you (1) do not remove any
								proprietary notice language in all copies of such documents, (2)
								use such information only for your personal, non-commercial
								informational purpose and do not copy or post such information
								on any networked computer or broadcast it in any media, (3) make
								no modifications to any such information, and (4) do not make
								any additional representations or warranties relating to such
								documents. You shall be responsible for any notes, messages,
								emails, billboard postings, photos, drawings, profiles,
								opinions, ideas, images, videos, audio files or other materials
								or information posted or transmitted to the website
								(collectively, "Content"). Such content will become our property
								and you grant us the worldwide, perpetual and transferable
								rights in such Content. We shall be entitled to, consistent with
								our Privacy Policy as adopted in accordance with applicable law,
								use the content or any of its elements for any type of use
								forever, including but not limited to promotional and
								advertising purposes and in any media whether now known or
								hereafter devised, including the creation of derivative works
								that may include the content you provide. You agree that any
								content you post may be used by us, consistent with our Privacy
								Policy and Rules of Conduct on website as mentioned herein, and
								you are not entitled to any payment or other compensation for
								such use.</p>
							<h3>Charges</h3>
							<p class="condition listtext">Membership on the Website is
								free for buyers. TryKaro does not charge any fee for browsing.
								TryKaro reserves the right to change any policy from time to
								time. In particular, TryKaro may at its sole discretion
								introduce new services and modify some or all of the existing
								services offered on the website. In such an event TryKaro
								reserves the right to introduce fees for the new services
								offered or amend/introduce fees for existing services, as the
								case may be. Changes to the fee policy shall be posted on the
								website and such changes shall automatically become effective
								immediately after they are posted on the Website. Unless
								otherwise stated, all fees shall be quoted in Indian Rupees. You
								shall be solely responsible for compliance of all applicable
								laws including those in India for making payments on TryKaro</p>
							<h3>Account Security</h3>
							<p class="condition listtext">After opening a TryKaro
								account, you accept all responsibility for any activity that
								occurs while logged into your account. You are responsible for
								making sure that you keep your password secure and safe. You
								agree that you will not share your password with others or do
								anything that might jeopardize the security of your account,
								including sharing your password with or logging in through
								unauthorized third-party applications or clients that attempt to
								access the TryKaro API. If you use any such application or
								client, you acknowledge and agree that TryKaro will bear no
								responsibility for any actions taken by those applications or
								clients, such as any breach or unauthorized use of your account
								information or messages.</p>
							<p class="condition listtext">When you first create a TryKaro
								account, we ask for your mobile number to verify your account.</p>
							<h3>Disclaimer</h3>

							<p class="condition listtext">
								This Website, all the materials and products (including but not
								limited to software) and services, included on or otherwise made
								available to you through this site are provided on "as is" and
								"as available" basis without any representation or warranties,
								express or implied except otherwise specified in writing.
								Without prejudice to the forgoing paragraph, TryKaro does not
								warrant that: <br />1)This Website will be constantly
								available, or available at all; or<br /> 2)The information on
								this Website is complete, true, accurate or non-misleading.
							</p>
							<h3>Questions and Comments</h3>
							<p class="condition listtext">
								TryKaro welcomes comments, questions, concerns, or suggestions.
								Please send feedback to us by visiting <a
									href="<%=request.getContextPath()%>/contactus">http:www.trykaro.com</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</section>
		<%@ include file="footer.jsp"%>
		<div id="scroll-top" class="_1">Scroll Top</div>
	</div>

</body>
</html>